#!/bin/bash -e

if hash xbuild &> /dev/null ; then
  BUILD=xbuild
  RUN=mono
elif hash msbuild.exe &> /dev/null ; then
  BUILD="msbuild.exe /maxcpucount"
  RUN=
else
  echo "Couldn't find build command."
  exit 1
fi

PAKET=.paket/paket.exe

$RUN .paket/paket.bootstrapper.exe -s --max-file-age=60
if [ ! -x $PAKET ] ; then
  chmod +x $PAKET
fi

$RUN $PAKET --silent restore

for SOLUTION in *.sln ; do
  for CONFIG in Debug Release ; do
    $BUILD /nologo /verbosity:quiet /p:Configuration=$CONFIG $SOLUTION
  done
done

for TEMPLATE in *.paket.template ; do
  $RUN $PAKET --silent pack output . templatefile $TEMPLATE
done

scripts/refgen

rm -rf .recall

for BENCHMARK in `ls Benchmarks` ; do
  if [ -e Benchmarks/$BENCHMARK/.skip ] ; then
    continue
  fi

  for CONFIG in Debug Release ; do
    EXE=Benchmarks/$BENCHMARK/bin/$CONFIG/$BENCHMARK.exe

    $RUN $EXE
    $RUN $EXE
    rm -rf .recall
  done
done
